# This is a basic workflow to help you get started with Actions

name: Dod1

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build & upload images to DockerHub
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3

      # Install & Setup QEMU
      - name: Docker Setup QEMU
        # You may pin to the exact commit or the version.
        # uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480
        uses: docker/setup-qemu-action@v1.2.0

      # Install & Setup Buildx
      - name: Docker Setup Buildx
        # You may pin to the exact commit or the version.
        # uses: docker/setup-buildx-action@f211e3e9ded2d9377c8cadc4489a4e38014bc4c9
        uses: docker/setup-buildx-action@v1.7.0
      
      # Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      # Build & publish to DockerHub
      - name: Build & Publish on DockerHub
        uses: docker/build-push-action@v2.10.0
        with:
          context: ./
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
          file: ./Dockerfile
          push: true
          tags: piotrpozarowszczyk1/zad1:dod1
          cache-from: type=registry, ref=piotrpozarowszczyk1/zad1:dod1
          cache-to: type=inline
          
      
          
          
          
          
